Task 11
miloserdova-l/formal-lang-course pull request #10
Opened 2021-11-21 18:51 UTC by miloserdova-l

# Задача 11. Тензорный алгоритм решения задачи достижимости с КС ограничениями

* **Мягкий дедлайн**: 21.11.2021, 23:59
* **Жёсткий дедлайн**: 24.11.2021, 23:59
* Полный балл: 5

## Задача

- [x] Реализовать **функцию**, основанную на тензорном алгоритме, решающую задачу достижимости между всеми парами вершин для заданного графа и заданной КС грамматики.
  - Результат работы функции --- множество троек вида (вершина, нетерминал, вершина).
  - Предусмотрите возможность получать граф из различных источников в различных форматах.
  - Предусмотрите возможность получать грамматику из различных источников (из файла, как результат работы других функций).
  - Для преобразования грамматики в РКА использовать результаты предыдущих работ.
  - Для реализации матричных операций использовать [sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html).
- [x] На основе предыдущей функции реализовать функцию, позволяющую решать задачу достижимости для заданного набора стартовых и финальных вершин, и заданного нетерминала.
- [x] Добавить необходимые тесты.

2021-11-24 09:57 UTC, EgorOrachyov requested changes

2021-11-24 09:57 UTC, EgorOrachyov commented on project/cfpq/tensor.py
> +        i += 1
1. Не очень понимаю, почему здесь происходит преобразование входной грамматики в rsm в виде набора матриц, если в предыдущих "подготовительных" задания, были функции `cfg_to_ecfg` и `ecfg_to_rsm`, которые дают желаемый результат, и далее из rsm можно было бы набор матриц переходов получить.

2021-11-24 09:57 UTC, EgorOrachyov commented on project/cfpq/tensor.py
> +            m = boxes.get(b.value, dok_matrix((n, n), dtype=bool))
2. Т.е. это было бы идеально либо как в метод rsm вынести (преобразование в матрицы), либо как отдельную функцию

2021-11-24 09:57 UTC, EgorOrachyov commented on project/cfpq/tensor.py
> +            triples.add((u, key, v))
3. Возможно `{(u, key, v) for key, m in g.edges.items() if key in nonterm for (u, v) in m}` было бы более элегантно. Более того, зачем метод `m.items()`, если значения игнорируются, и итерирование для словарей (если это словарь), по ключам по умолчанию.

2021-11-24 10:02 UTC, EgorOrachyov commented on project/cfpq/tensor.py
> +                g.edges[variable] = m
4. Можно упростить, ведь если хотя бы у одной матрицы поменялось количество ненулевых элементов, значит фиксированная точка еще не достигнута, и надо продолжать. Можно либо на матрицы смежности смотреть, либо на результат транзитивного замыкания (кол-во ненулевых элементов после tc - если поменялось, значит точно что-то новое нашли).

2021-11-24 20:13 UTC, miloserdova-l commented on project/cfpq/tensor.py
> +            triples.add((u, key, v))
Это не словарь, а матрица

2021-11-29 12:26 UTC, EgorOrachyov approved these changes

2021-11-29 12:26 UTC, EgorOrachyov commented on project/cfpq/tensor.py
> +    ecfg = cfg_to_ecfg(cfg)
```python
ecfg = cfg_to_ecfg(cfg)
nonterm = {p.value for p in ecfg.productions}
```

2021-11-29 12:26 UTC, EgorOrachyov commented on project/cfpq/tensor.py
> +    ecfg = cfg_to_ecfg(cfg)
Поправить это и можно мерджить

2021-12-02 08:41 UTC, merged