Task 5
miloserdova-l/formal-lang-course pull request #13
Opened 2021-12-24 16:57 UTC by miloserdova-l

# Задача 5. Экспериментальное исследование алгоритмов для регулярных запросов

* **Мягкий дедлайн**: 06.10.2021, 23:59
* **Жёсткий дедлайн**: 13.10.2021, 23:59
* Полный балл: 11

## Задача

Задача посвящена анализу производительности различных реализаций алгоритма решения задачи достижимости между всеми парами вершин с регулярными ограничениями через тензорное произведение.

[Ссылка на ноутбук](https://colab.research.google.com/drive/1bnRQSKiWtR397Vb0z3EJS_x3S_BklCZi?usp=sharing)

- [x] Используя [pyCuBool](https://pypi.org/project/pycubool/) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение. Аналогично тому, как это было сделано в предыдущей домашней работе. Лучше сразу предусмотреть общий интерфейс функций, чтобы было проще ставить эксперименты.
- [x] Подключить решение из предыдущей работы.
- [x] Сформировать набор данных.
  - [x] Выбрать все графы из раздела [RDF](https://jetbrains-research.github.io/CFPQ_Data/dataset/RDF.html).
  - [x] Используя функцию из первой домашней работы узнать метки рёбер графов и на основе этой информации сформулировать не менее четырёх различных запросов к каждому графу. Требования к запросам:
      - Запросы ко всем графам должны следовать некоторому общему шаблону. Например, если есть графы ```g1``` и ```g2``` с различными наборами меток, то ожидается, что запросы к ним будут выглядеть, например, так:
        - ```g1```:
          - ```(l1 | l2)* l3```
          - ```(l3 | l4)+ l1*```
          - ```l1 l2 l3 (l4|l1)*```
        - ```g2```:
          - ```(m1 | m3)* m2```
          - ```(m1 | m3)+ m2*```
          - ```m1 m2 m3 (m3|m1)*```
      - В запросах должны использоваться все общепринятые конструкции регулярных выражений  (замыкание, конкатенация, альтернатива). То есть хотя бы в одном запросе к каждому графу должна быть каждая из этих конструкций.
- [x] С использованием сформированного набора данных провести сравнение производительности алгоритма, основанного на тензорном произведении, реализованного с использованием двух библиотек
  - sciPy (предыдущая работа)
  - pyCuBool (первый пункт этой работы)
- [ ] Оформить результаты экспериментов
- [ ] Провести анализ результатов
- [x] Сделать notebook доступным по ссылке (не забыть проверить, что выданы пава на комментирование)

2021-12-25 10:12 UTC, EgorOrachyov requested changes

2021-12-25 10:12 UTC, EgorOrachyov commented on .github/workflows/test.yml
> -        os: [ubuntu-latest, macos-latest, windows-latest]
Сужать CI с 3х платформ до одной, однозначно, не стоит.
Тк используется pycubool, который только под ubuntu, я бы не добавлял его в requirements, 
А так где он использовался, сделал проверку `if ubuntun: import pycubool`. 
В ноутбуке с экспериментами просто в начале добавить отдельный шаг в ячейку `pip install pycubool`

2021-12-25 10:12 UTC, EgorOrachyov commented on benchmark/rpq_pycubool/atom_primitive.csv
> +Query,RPQ_size,Time(s)
Не стоит выкладывать какие-либо данные, отличие от кода, связанные с запуском/результатами бенчмарков.
Графиков внутри ноутбука, которые там уже есть, вполне достаточно. Поэтому я бы предложил удалить это пару csv'шек (если они больше нигде не нужны)

2021-12-25 10:12 UTC, EgorOrachyov commented on tests/test_rpq.py
> +    assert ans == expected
Можно сделать if, и тестировать pycubool только на linux

2021-12-25 13:19 UTC, miloserdova-l commented on benchmark/rpq_pycubool/atom_primitive.csv
> +Query,RPQ_size,Time(s)
Так как в колабе удаляются файлы, чтобы результаты не пересчитывать (а на это уходит время и нервы), удобно хранить файлы в репозитории (например, если захочется построить новые графики или еще что-то проанализировать)

2022-01-24 08:32 UTC, EgorOrachyov approved these changes

2022-01-24 08:40 UTC, merged