Task 4
miloserdova-l/formal-lang-course pull request #4
Opened 2021-09-26 17:26 UTC by miloserdova-l

# Задача 4. Регулярные запросы

* **Мягкий дедлайн**: 26.09.2021, 23:59
* **Жёсткий дедлайн**: 29.09.2021, 23:59
* Полный балл: 5

## Задача

- [x] Используя [разреженные матрицы из sciPy](https://docs.scipy.org/doc/scipy/reference/sparse.html) реализовать алгоритм пересечения двух конечных автоматов через тензорное произведение.
- [x] На основе реализованного алгоритма реализовать **функцию** выполнения регулярных запросов к графам. Не забыть предоставить возможность задавать стартовые и финальные вершины в графе.
  - Для конструирования регулярного запроса использовать результаты [Задачи 2](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task2.md).
  - Для преобразования графа использовать результаты [Задачи 3](https://github.com/JetBrains-Research/formal-lang-course/blob/main/tasks/task3.md).
- [x] Добавить необходимые тесты.

2021-09-27 14:32 UTC, EgorOrachyov commented on project/rpq.py
> +    new_r = Automaton(r)
Лучше на вход получать запрос, граф, стартовые и финальные состояния, а автоматы внутри конструировать (собственно, как в тг обсуждалось)

2021-09-27 14:35 UTC, EgorOrachyov commented on tests/test_rpq.py
> +    """
Этот тест скорее относится к `class Automaton`, поэтому его можно в отдельный файл вынести

2021-09-27 14:38 UTC, EgorOrachyov commented on project/finite_automaton_utils.py
> +    def __init__(self, fa: FiniteAutomaton):
Возможно, стоит дать более специфичное название, тк это конечный автомат, но с булевой декомпозицией.
Возможно, может даже в отдельный файл вынести

2021-09-27 14:40 UTC, EgorOrachyov commented on project/finite_automaton_utils.py
> +            exit(1)
Пересечение двух автоматов это, на самом деле, тоже новый автомат. Поэтому, для аккуратности, я бы предложил здесь делать новый автомат, а не одну матрицу. А потом уже, например в `rpq` и или `tc` шаге, мерджить матрицы (`sum all`) и т.д.

2021-10-01 13:59 UTC, EgorOrachyov requested changes

2021-10-01 13:59 UTC, EgorOrachyov commented on project/finite_automaton_utils.py
> +        return BoolFiniteAutomaton(fa)
Не понимаю, зачем полученные на вход разреженные булевы матрицы перегонять в `NondeterministicFiniteAutomaton`, чтобы на его основе опять строить `BoolFiniteAutomaton`. Речь идет о миллионах вершин и переходов. После пересечения `intersection` матрица переходов уже есть. Надо всего лишь состояния добавлять и все - новый `BoolFiniteAutomaton` готов

2021-10-01 13:59 UTC, EgorOrachyov commented on tests/test_rpq.py
> +    assert ans == {(0, 0), (0, 3), (0, 5), (1, 3), (1, 5), (1, 0)}
Напрашивается `@pytest.mark.parametrize`

2021-10-01 18:25 UTC, miloserdova-l commented on project/finite_automaton_utils.py
> +        return BoolFiniteAutomaton(fa)
Кажется, это может наоборот ускорить, так как размер матрицы может уменьшиться, а далее нужно будет найти транзитивное замыкания уже уменьшенной матрицы

2021-10-03 08:52 UTC, EgorOrachyov commented on project/finite_automaton_utils.py
> +        return BoolFiniteAutomaton(fa)
Время выполнения умножения и сложения (а как следствие, транзитивного замыкания) для разреженных матриц зависит только то количества ненулувых элементов в матрице (большинство хороших алгоритмов так устроены). Уменьшение размерности матрицы ни на что не влияет. А кол-во ненулевых элементов не уменьшить, тк это переходы - и для вычисления tc они нужны.

2021-10-03 14:00 UTC, EgorOrachyov approved these changes

2021-10-03 15:40 UTC, merged